[build]
  base = "."
  publish = "frontend/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"